# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcluster.proto\"/\n\rResumeRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\" \n\x0eResumeResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"0\n\x0eSuspendRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"!\n\x0fSuspendResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"6\n\x14\x43lusterStatusRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\'\n\x15\x43lusterStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa2\x01\n\x0e\x43lusterService\x12)\n\x06resume\x12\x0e.ResumeRequest\x1a\x0f.ResumeResponse\x12,\n\x07suspend\x12\x0f.SuspendRequest\x1a\x10.SuspendResponse\x12\x37\n\x06status\x12\x15.ClusterStatusRequest\x1a\x16.ClusterStatusResponseB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _globals['_RESUMEREQUEST']._serialized_start=17
  _globals['_RESUMEREQUEST']._serialized_end=64
  _globals['_RESUMERESPONSE']._serialized_start=66
  _globals['_RESUMERESPONSE']._serialized_end=98
  _globals['_SUSPENDREQUEST']._serialized_start=100
  _globals['_SUSPENDREQUEST']._serialized_end=148
  _globals['_SUSPENDRESPONSE']._serialized_start=150
  _globals['_SUSPENDRESPONSE']._serialized_end=183
  _globals['_CLUSTERSTATUSREQUEST']._serialized_start=185
  _globals['_CLUSTERSTATUSREQUEST']._serialized_end=239
  _globals['_CLUSTERSTATUSRESPONSE']._serialized_start=241
  _globals['_CLUSTERSTATUSRESPONSE']._serialized_end=280
  _globals['_CLUSTERSERVICE']._serialized_start=283
  _globals['_CLUSTERSERVICE']._serialized_end=445
# @@protoc_insertion_point(module_scope)
